language: php
sudo: required

php:
  - '7.1'

before_script:
  - composer require yiisoft/yii2-codeception
  - composer require codeception/base
  - composer require codeception/verify
  - composer require codeception/specify
  - composer require codeception/codeception
  - composer require satooshi/php-coveralls
  - mkdir -p build/logs

script:
  - tests/unit.sh

after_success:
  - php vendor/bin/coveralls -v